// audit-topics.ts
export enum AuditTopic {
    LOGIN = 'LOGIN',
    LOGOUT = 'LOGOUT',
    USER_CREATE = 'USER_CREATE',
    USER_DELETE = 'USER_DELETE',
    VEHICLE_CREATE = 'VEHICLE_CREATE',
    VEHICLE_DELETE = 'VEHICLE_DELETE',
    PERMISSION_GRANT = 'PERMISSION_GRANT',
    PERMISSION_REVOKE = 'PERMISSION_REVOKE',
    DEVICE_BIND = 'DEVICE_BIND',
    DEVICE_UNBIND = 'DEVICE_UNBIND',
    HTTP_REQUEST = 'HTTP_REQUEST',
    ENTITY_INSERT = 'ENTITY_INSERT',
    ENTITY_UPDATE = 'ENTITY_UPDATE',
    ENTITY_REMOVE = 'ENTITY_REMOVE',
    EXCEPTION = 'EXCEPTION',
    USER_UPDATE = 'USER_UPDATE',        // تغییر نام/موبایل
    USER_CHANGE_PASSWORD = 'USER_CHANGE_PASSWORD',// تغییر رمز
    USER_CHANGE_ROLE = 'USER_CHANGE_ROLE',        // تغییر نقش
    USER_SET_PERMISSIONS = 'USER_SET_PERMISSIONS',   // تغییر مجوزهای اکشنی
    PERMISSION_UPDATE = 'PERMISSION_UPDATE', // آپدیت‌های دسته‌ای (گرفت/داد)
    PERMISSION_SYNC = 'PERMISSION_SYNC',     // سید دسته‌جمعی
    POLICY_UPDATE = 'POLICY_UPDATE',               // ⬅️ اضافه
    COUNTRY_POLICY_UPDATE = 'COUNTRY_POLICY_UPDATE' // ⬅️ (اگه لازم داری)
}
